CREATE TABLE
  BRANCH (
    BRANCHID INT NOT NULL,
    NAME VARCHAR2 (100) NOT NULL,
    DISTRICT VARCHAR2 (100),
    PROFIT NUMBER (12, 2),
    CONSTRAINT BRANCH_PK PRIMARY KEY (BRANCHID) ENABLE
  );