CREATE TABLE
  BRAND (
    BRANDID NUMBER NOT NULL,
    NAME VARCHAR2 (100) NOT NULL,
    CATEGORYID NUMBER,
    ORIGIN VARCHAR2 (100),
    CONSTRAINT BRAND_PK PRIMARY KEY (BRANDID) ENABLE
  );

ALTER TABLE BRAND ADD CONSTRAINT BRAND_CATEGORYID_FK FOREIGN KEY (CATEGORYID) REFERENCES CATEGORY (CATEGORYID) ENABLE;