CREATE TABLE
  CUSTOMER (
    CUSTOMERID INT NOT NULL,
    NAME VARCHAR2 (100) NOT NULL,
    ADDRESS VARCHAR2 (255),
    PHONENUMBER NUMBER (15),
    EMAIL VARCHAR2 (100),
    CONSTRAINT CUSTOMER_PK PRIMARY KEY (CUSTOMERID) ENABLE
  );