CREATE TABLE
  EMPLOYEE (
    EMPLOYEEID NUMBER NOT NULL,
    NAME VARCHAR2 (100) NOT NULL,
    POSITION VARCHAR2 (50),
    SALARY NUMBER (10, 2),
    ADDRESS VARCHAR2 (255),
    BRANCHID NUMBER,
    CONSTRAINT EMPLOYEE_PK PRIMARY KEY (EMPLOYEEID) ENABLE
  );

ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_BRANCH_FK1 FOREIGN KEY (BRANCHID) REFERENCES BRANCH (BRANCHID) ENABLE;