CREATE TABLE
  ITEM (
    ITEMID NUMBER NOT NULL,
    NAME VARCHAR2 (100) NOT NULL,
    DESCRIPTION CLOB,
    PRICE NUMBER (10, 2) NOT NULL,
    STOCKQUANTITY NUMBER NOT NULL,
    BRANDID NUMBER,
    CATEGORYID NUMBER,
    CONSTRAINT ITEM_PK PRIMARY KEY (ITEMID) ENABLE
  );

ALTER TABLE ITEM ADD CONSTRAINT ITEM_BRAND_FK1 FOREIGN KEY (BRANDID) REFERENCES BRAND (BRANDID) ENABLE;

ALTER TABLE ITEM ADD CONSTRAINT ITEM_CATEGORY_FK1 FOREIGN KEY (CATEGORYID) REFERENCES CATEGORY (CATEGORYID) ENABLE;