CREATE TABLE
  ORDER_ITEM (
    ORDERITEMID NUMBER NOT NULL,
    ORDERID NUMBER,
    ITEMID NUMBER,
    QUANTITY NUMBER NOT NULL,
    UNITPRICE NUMBER (10, 2) NOT NULL,
    TOTALPRICE NUMBER (12, 2),
    CONSTRAINT ORDER_ITEM_PK PRIMARY KEY (ORDERITEMID) ENABLE
  );

ALTER TABLE ORDER_ITEM ADD CONSTRAINT ORDER_ITEM_ITEM_FK1 FOREIGN KEY (ITEMID) REFERENCES ITEM (ITEMID) ENABLE;

ALTER TABLE ORDER_ITEM ADD CONSTRAINT ORDER_ITEM_ORDER_FK1 FOREIGN KEY (ORDERID) REFERENCES ORDERS (ORDERID) ENABLE;