CREATE TABLE
  PAYMENT (
    PAYMENTID NUMBER NOT NULL,
    METHOD VARCHAR2 (50),
    PAYMENTDATETIME TIMESTAMP,
    AMOUNT NUMBER (10, 2) NOT NULL,
    CONSTRAINT PAYMENT_PK PRIMARY KEY (PAYMENTID) ENABLE
  );