CREATE TABLE
  SALES (
    SALESID NUMBER NOT NULL,
    BRANCHID NUMBER,
    SALEDATE DATE NOT NULL,
    TOTALSALESAMOUNT NUMBER (12, 2),
    CONSTRAINT SALES_PK PRIMARY KEY (SALESID) ENABLE
  );

ALTER TABLE SALES ADD CONSTRAINT SALES_BRANCH_FK1 FOREIGN KEY (BRANCHID) REFERENCES BRANCH (BRANCHID) ENABLE;