CREATE TABLE
  SUPPLY (
    SUPPLYID NUMBER NOT NULL,
    SUPPLIERID NUMBER,
    ITEMID NUMBER,
    QUANTITY NUMBER NOT NULL,
    SUPPLYDATE DATE,
    CONSTRAINT SUPPLY_PK PRIMARY KEY (SUPPLYID) ENABLE
  );

ALTER TABLE SUPPLY ADD CONSTRAINT SUPPLY_ITEM_FK1 FOREIGN KEY (ITEMID) REFERENCES ITEM (ITEMID) ENABLE;

ALTER TABLE SUPPLY ADD CONSTRAINT SUPPLY_SUPPLIER_FK1 FOREIGN KEY (SUPPLIERID) REFERENCES SUPPLIER (SUPPLIERID) ENABLE;