CREATE TABLE
  SUPPLIER (
    SUPPLIERID NUMBER NOT NULL,
    NAME VARCHAR2 (100) NOT NULL,
    CONTACTINFO VARCHAR2 (255),
    ORIGIN VARCHAR2 (100),
    CONSTRAINT SUPPLIER_PK PRIMARY KEY (SUPPLIERID) ENABLE
  );